language: node_js
node_js: stable
before_script:
- bower install --silent
addons:
  sauce_connect: true
script:
- npm run lint
- polymer test --plugin sauce --job-name "drop-file-importer:${TRAVIS_BRANCH}" --build-number=${TRAVIS_BUILD_NUMBER}
cache:
  directories:
  - node_modules
branches:
  only:
  - stage
  - develop
after_success:
- node tasks/ci.js
env:
  global:
  - secure: cjCre2ZCADSMO+u4ZY/43CI/ne2SeXTvmBrMYvi26131M1fQUiFiAVZbCEzmyKai3cezNjLKQwkwvohYQu0J73Tq0nBx84MDPDREzP9iinhJSPm29yRHz0ekWQbN6odk5LfhEjBetdppjH8v0lA8xy7y2cf92ynZv1/t4/T7QJ2HhpJZyOcV10Ha6+edAHygRvjqIXbY+ALH8v1pzQ2gQkUgD/neUhgvYuARHLdWM4UlaZcvOP8R7Sg9DqvGQVGz5s9hbZzyPb5tJ/GlYa/REsKS7oYUNBFt9OlrRumfu2hBcoddA9dwQHgJqErdBjxN+mMcCICKWFEoTa1O/tGnuY39be2AG0fBweHA+/38OR44EIhw8xq3Dnwm3P88wyL38FzGCNI7cAcoq07PTdbuiNpUYF/3JLImGKXhH92L4zshR2G6OUtb+Si9lw6Ity24jfq39kMbW/HwCK21GiU+c7g+NaIVOyoADk3B9iDLXtdg3VJCgrGMwN+worRZMI/Fbv9Hwn+RnLsfRf0nrcoU2aCYR/x6mJDX21MuvtqQl5TCUi2wi0WP3lGYNh3NbJMcUp/lmjwCZ9p1n5rG+MC051aAQgiV0YQd/NVUNdEmQbH91NrfqhukX6pwZNpsJRNMkTu5eUmXMxcWfY72XifW4gWxH73bshzVtL+z2Gi+LEw=
  - secure: Kq03euxmOr5J0TiqpF7SvqU/AMg3mWm0KtERszzlAkKGpDDSYSh3RQ2Sr/MijLbTkC+t5hX8uSgEtz8usfBfSXH1QMuLKCm42OhQ/cWV/dQHBAaqWET8qi1obTDGh23tQnWka6wo1o/vbnqCkun35WKVEhzTWuCUD7k7FQo6FU7V9uPBtO67376zjYhgSSNUbAVBviPYzFeQS0YSSUszoPPorvgdTWzitqKNmL8QcSqTwayBS1TNTkuDmiUz0cNAn9xPYsXuW0gK15+hROSPPIuGciERrgxFQ62c+LBG0jGyGwQj76UO6TF7r8B9X6yc5xQpG7ezRMfxZkOi2wvrcdWprjleQuO9XpxX+AZTojGIb8aMKSS7GXCG93hTfNpJwvV0ps/K6AeBbGwK8F1RLoLwn/xzjhtFAXDHN8STSg3y1Gr9WSc7UC7/XUN31Est2cHKFwdv5iLFnR642wRhvPlk2NceU4HJze8BtjwSgnzKOhzMBPYKN9uKUMqAvS7p2qYOH+YTaKaSEcpdidY1bsHnFfFxR7EDQ8BU+zEeQotMaLQCq8ic+npnjXt0Jos2MSsBlnaXi63UweucchLiltghMOM4F+FDJ/1vzrx6cXLxfbPpOGU0Eb9M46D7bR86V4YaqGmyiO0/wKBwI4D83UKZfDWr/VqQo9AZu1te0Fs=
